version: "3"

services:

  app1:
    build: .
    container_name: nodejs
    restart: always
    command: npm start
    ports:
      - 3000:3000
  
  db:
    container_name: mariadb
    build: ./build_db
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
    restart: always